### ISSUE TITLE
Submodules har försvunnit

### ISSUE THREAD

**Issue by cruzzan** [kodsnack/advent_of_code_2017#191]
Det verkar som att vi som checkat in våra bidrag som sub-moduler har fått dom borttagna ur repot. Oklart varför, vill ni inte att vi ska checka in grejer så?

**Comment by Meldanya** [comment]
Ser ut att ha hänt oavsiktligt i #115, de har lagts tillbaka i #187.

**Comment by bjoreman** [comment]
Ja, det var nog jag som gjorde bort mig i webb-UI:t en gång. Har lärt mig att vara mer hands off sedan dess :-) …

**Comment by cruzzan** [comment]
Hehe då var det inte jag som var galen då. Men nice, det verkar funka igen osv :) :+1:
